---
- name: STATUSINVEST Module
  hosts: localhost

  vars:
    acoes: 'petr4'
    fundos: 'hgre11'

  tasks:
    - name: Usando o modulo diretamente
      laurobmb.statusinvest.statusinvest:
        statusinvest_acoes: "{{ acoes }}"
        statusinvest_fundos: "{{ fundos }}"
      register: greeting

    - name: Debug modulo
      ansible.builtin.debug:
        msg: "{{ greeting }}"
