---
- name: STATUSINVEST
  hosts: localhost
  vars:
    acoes: 'petr4'
    fundos: 'hgre11'
  roles:
    - role: laurobmb.statusinvest.getdata

#   tasks:
#    - name: Usando o modulo diretamente
#      laurobmb.statusinvest.statusinvest:
#        statusinvest_acoes: "{{ acoes }}"
#        statusinvest_fundos: "{{ fundos }}"
#      register: greeting
#      vars:
#        acoes: 'bbas3'
#        fundos: 'vghf11'
#
#    - name: Debug modulo
#      ansible.builtin.debug:
#        msg: "{{ greeting }}"
#